import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-5 bg-gray-200">
        <main className="mx-auto rounded bg-white max-w-5xl px-5 min-h-[100dvh]">
          {children}
        </main>
      </body>
    </html>
  );
}
